version: '3.9'
services:
    db:
        image: postgres
        user: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
    web: &app_base
        build:
          context: .
          dockerfile: Dockerfile-ruby
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - .:/myapp
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: development
        depends_on:
            - db
    mecab:
      build: 
        context: .
        dockerfile: Dockerfile-mecab